#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-columnize
Version  : 0.3.10
Release  : 1
URL      : https://files.pythonhosted.org/packages/61/ce/9bdb7374937445534b1b9b583aabdaf4204fa1b4cfa66d6844b39fbb564e/columnize-0.3.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/61/ce/9bdb7374937445534b1b9b583aabdaf4204fa1b4cfa66d6844b39fbb564e/columnize-0.3.10.tar.gz
Summary  : Format a simple (i.e. not nested) list into aligned columns.
Group    : Development/Tools
License  : MIT
Requires: pypi-columnize-python = %{version}-%{release}
Requires: pypi-columnize-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(mock)
BuildRequires : pypi(nose)

%description
|packagestatus|
        
        In showing a long lists, sometimes one would prefer to see the value
        arranged aligned in columns. Some examples include listing methods of an
        object, listing debugger commands, or showing a numeric array with data
        aligned.
        
        This is a Python module to format a simple (i.e. not nested) list into
        aligned columns. A string with embedded newline characters is returned.
        
        Setup
        -----

%package python
Summary: python components for the pypi-columnize package.
Group: Default
Requires: pypi-columnize-python3 = %{version}-%{release}

%description python
python components for the pypi-columnize package.


%package python3
Summary: python3 components for the pypi-columnize package.
Group: Default
Requires: python3-core
Provides: pypi(columnize)

%description python3
python3 components for the pypi-columnize package.


%prep
%setup -q -n columnize-0.3.10
cd %{_builddir}/columnize-0.3.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642084422
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
